'use client'
import Link from 'next/link'
import { useLocale } from 'next-intl'

const CONTENT = {
  en: {
    title: 'Terms of Service',
    date: 'Effective: May 7, 2026',
    operator: 'PilLAB  |  Representative: Park Junpil  |  Contact: bbiribbiri09@gmail.com',
    back: '← Back',
    privacy: 'Privacy Policy',
    refund: 'Refund Policy',
    sections: [
      {
        h: '1. About This Service',
        p: 'AstroPillar provides fortune readings based on Eastern BaZi (Four Pillars) and Western astrology. All readings are for entertainment and informational purposes only. They do not constitute professional advice of any kind — including medical, legal, financial, or psychological advice. We make no guarantees regarding the accuracy or outcomes of any reading.',
      },
      {
        h: '2. Eligibility',
        p: 'You must be at least 13 years of age to use AstroPillar. By creating an account, you confirm that you meet this requirement. Users under 18 should obtain parental consent before using paid services.',
      },
      {
        h: '3. Account',
        p: 'You are responsible for maintaining the security of your account credentials. One account per person is permitted. You may not share, sell, or transfer your account to another person. We reserve the right to suspend or terminate accounts that violate these Terms.',
      },
      {
        h: '4. Credits',
        p: 'Credits are the in-app currency used to unlock premium fortune readings.\n• Credits are non-transferable and cannot be exchanged for cash\n• Credits expire 1 year from the date of purchase\n• Used credits are non-refundable\n• We are not responsible for credits lost due to account termination resulting from Terms violations',
      },
      {
        h: '5. Acceptable Use',
        p: 'You agree not to:\n• Use the service for any unlawful purpose\n• Attempt to reverse-engineer, scrape, or automate access to the service\n• Resell or redistribute readings or content\n• Upload harmful, fraudulent, or offensive content',
      },
      {
        h: '6. Intellectual Property',
        p: 'All content, design, code, and readings generated by AstroPillar are the intellectual property of PilLAB. You may not reproduce, distribute, or create derivative works without prior written permission.',
      },
      {
        h: '7. Disclaimer',
        p: 'AstroPillar is provided "as is" without any warranty. We do not guarantee uninterrupted access to the service. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service.',
      },
      {
        h: '8. Changes to Terms',
        p: 'We may update these Terms at any time. Continued use of the service following any changes constitutes your acceptance of the revised Terms. We will notify users of material changes via the app or email.',
      },
      {
        h: '9. Governing Law',
        p: 'These Terms are governed by the laws of the Republic of Korea. Any disputes shall be subject to the exclusive jurisdiction of the courts in Seoul, Republic of Korea.',
      },
      {
        h: '10. Contact',
        p: 'For any questions about these Terms:\nEmail: bbiribbiri09@gmail.com',
      },
    ],
  },
  ko: {
    title: '이용약관',
    date: '시행일: 2026년 5월 7일',
    operator: '필랩(PilLAB)  |  대표자: 박준필  |  문의: bbiribbiri09@gmail.com',
    back: '← 뒤로',
    privacy: '개인정보처리방침',
    refund: '환불정책',
    sections: [
      {
        h: '1. 서비스 소개',
        p: 'AstroPillar는 동양 사주명리(사주팔자)와 서양 점성술을 기반으로 운세 리딩 서비스를 제공합니다. 모든 리딩은 오락 및 정보 제공 목적으로만 제공되며, 의료·법률·금융·심리 등 전문적 조언을 대체하지 않습니다. 리딩 결과의 정확성이나 특정 결과를 보증하지 않습니다.',
      },
      {
        h: '2. 이용 자격',
        p: 'AstroPillar를 이용하려면 만 13세 이상이어야 합니다. 계정을 생성함으로써 해당 조건을 충족함을 확인합니다. 만 18세 미만의 이용자는 유료 서비스 이용 전 보호자의 동의를 받아야 합니다.',
      },
      {
        h: '3. 계정',
        p: '이용자는 계정 보안에 책임을 집니다. 1인 1계정 원칙이 적용되며, 계정의 양도·판매·공유를 금지합니다. 본 약관을 위반한 계정은 정지 또는 삭제될 수 있습니다.',
      },
      {
        h: '4. 크레딧',
        p: '크레딧은 유료 운세 리딩을 이용하기 위한 앱 내 화폐입니다.\n• 크레딧은 양도 불가하며 현금으로 교환할 수 없습니다\n• 크레딧은 구매일로부터 1년간 유효합니다\n• 사용된 크레딧은 환불되지 않습니다\n• 약관 위반으로 인한 계정 정지·삭제 시 잔여 크레딧은 복구되지 않습니다',
      },
      {
        h: '5. 금지 행위',
        p: '이용자는 다음의 행위를 해서는 안 됩니다.\n• 불법적인 목적으로 서비스를 이용하는 행위\n• 서비스를 역분석, 크롤링, 자동화 방식으로 접근하는 행위\n• 리딩 내용 또는 콘텐츠를 재판매하거나 배포하는 행위\n• 유해하거나 허위의 콘텐츠를 업로드하는 행위',
      },
      {
        h: '6. 지식재산권',
        p: 'AstroPillar의 모든 콘텐츠, 디자인, 코드 및 리딩 결과물은 필랩(PilLAB)의 지식재산입니다. 사전 서면 허가 없이 복제, 배포, 2차 저작물 제작이 금지됩니다.',
      },
      {
        h: '7. 면책 조항',
        p: 'AstroPillar는 "있는 그대로(as is)" 제공됩니다. 서비스의 중단 없는 이용을 보장하지 않으며, 서비스 이용으로 인한 간접적·부수적·결과적 손해에 대해 책임을 지지 않습니다.',
      },
      {
        h: '8. 약관 변경',
        p: '본 약관은 언제든지 변경될 수 있습니다. 변경 후 서비스를 계속 이용할 경우 변경된 약관에 동의한 것으로 간주됩니다. 중요한 변경 사항은 앱 또는 이메일을 통해 고지합니다.',
      },
      {
        h: '9. 준거법 및 관할',
        p: '본 약관은 대한민국 법률에 따라 규율됩니다. 분쟁 발생 시 대한민국 서울 법원을 전속 관할 법원으로 합니다.',
      },
      {
        h: '10. 문의',
        p: '약관에 관한 문의:\n이메일: bbiribbiri09@gmail.com',
      },
    ],
  },
  ja: {
    title: '利用規約',
    date: '施行日: 2026年5月7日',
    operator: 'PilLAB  |  代表: Park Junpil  |  お問い合わせ: bbiribbiri09@gmail.com',
    back: '← 戻る',
    privacy: 'プライバシーポリシー',
    refund: '返金ポリシー',
    sections: [
      {
        h: '1. サービスについて',
        p: 'AstroPillarは、東洋の四柱推命と西洋占星術に基づいた占いサービスを提供します。すべての鑑定は娯楽・情報提供を目的としたものであり、医療・法律・財務・心理的なアドバイスの代替にはなりません。鑑定結果の正確性や特定の結果については保証いたしません。',
      },
      {
        h: '2. 利用資格',
        p: 'AstroPillarを利用するには13歳以上である必要があります。アカウントを作成することで、この条件を満たすことを確認したものとみなします。18歳未満のユーザーは、有料サービスを利用する前に保護者の同意を得てください。',
      },
      {
        h: '3. アカウント',
        p: 'ユーザーはアカウントのセキュリティに責任を負います。1人につき1アカウントのみ許可されます。アカウントの譲渡・販売・共有は禁止されています。本規約に違反したアカウントは停止または削除される場合があります。',
      },
      {
        h: '4. クレジット',
        p: 'クレジットはプレミアム占い鑑定を利用するためのアプリ内通貨です。\n• クレジットは譲渡不可であり、現金に交換することはできません\n• クレジットは購入日より1年間有効です\n• 使用済みクレジットは返金されません\n• 規約違反によるアカウント停止・削除の場合、残クレジットは復元されません',
      },
      {
        h: '5. 禁止行為',
        p: '以下の行為を行わないことに同意します。\n• 違法な目的でサービスを利用すること\n• サービスのリバースエンジニアリング、スクレイピング、自動アクセスを試みること\n• 鑑定内容やコンテンツを再販・配布すること\n• 有害・虚偽・不適切なコンテンツをアップロードすること',
      },
      {
        h: '6. 知的財産権',
        p: 'AstroPillarのすべてのコンテンツ、デザイン、コード、鑑定結果はPilLABの知的財産です。事前の書面による許可なく、複製、配布、二次著作物の作成を禁じます。',
      },
      {
        h: '7. 免責事項',
        p: 'AstroPillarは「現状のまま」提供されます。サービスの中断のない利用を保証するものではなく、サービス利用に起因する間接的・付随的・結果的損害について責任を負いません。',
      },
      {
        h: '8. 規約の変更',
        p: '本規約はいつでも変更される場合があります。変更後もサービスを継続利用することで、改訂された規約に同意したものとみなします。重要な変更はアプリまたはメールでお知らせします。',
      },
      {
        h: '9. 準拠法・管轄',
        p: '本規約は大韓民国の法律に準拠します。紛争が生じた場合、ソウルの裁判所を専属管轄裁判所とします。',
      },
      {
        h: '10. お問い合わせ',
        p: '本規約に関するお問い合わせ:\nメール: bbiribbiri09@gmail.com',
      },
    ],
  },
}

export default function TermsPage() {
  const locale = useLocale()
  const c = CONTENT[locale as keyof typeof CONTENT] ?? CONTENT.en
  const prefix = locale === 'en' ? '' : `/${locale}`
  const ff = locale === 'ko' ? "'Noto Sans KR', sans-serif" : locale === 'ja' ? "'Noto Sans JP', sans-serif" : "'Noto Sans', sans-serif"

  return (
    <main style={{ fontFamily: ff, background: '#07071a', color: '#F6F6F8', minHeight: '100vh', paddingBottom: 48 }}>
      <div style={{ position: 'sticky', top: 0, zIndex: 100, display: 'flex', alignItems: 'center', gap: 14, padding: '14px 20px', background: 'rgba(10,10,26,0.97)', borderBottom: '1px solid rgba(201,168,76,.12)' }}>
        <Link href={prefix || '/'} style={{ color: 'rgba(201,168,76,.65)', fontSize: 13, textDecoration: 'none', whiteSpace: 'nowrap' }}>{c.back}</Link>
        <span style={{ color: '#C9A84C', fontSize: 12, fontWeight: 900, letterSpacing: '2.5px', fontFamily: "'Cormorant Garamond', serif" }}>ASTROPILLAR</span>
      </div>

      <div style={{ maxWidth: 640, margin: '0 auto', padding: '32px 24px' }}>
        <div style={{ marginBottom: 28, paddingBottom: 22, borderBottom: '1px solid rgba(201,168,76,.12)' }}>
          <h1 style={{ fontSize: 22, fontWeight: 700, color: '#C9A84C', margin: '0 0 10px' }}>{c.title}</h1>
          <p style={{ fontSize: 12, color: 'rgba(200,195,220,.45)', marginBottom: 6 }}>{c.date}</p>
          <p style={{ fontSize: 11, color: 'rgba(200,195,220,.35)', lineHeight: 1.7 }}>{c.operator}</p>
        </div>

        {c.sections.map((s, i) => (
          <div key={i} style={{ marginBottom: 28 }}>
            <h2 style={{ fontSize: 14, fontWeight: 700, color: '#C9A84C', margin: '0 0 10px' }}>{s.h}</h2>
            {s.p.split('\n').map((line, j) => (
              <p key={j} style={{
                fontSize: 13, lineHeight: 1.85, color: 'rgba(200,195,220,.75)',
                margin: `0 0 ${line.startsWith('•') ? 3 : 8}px`,
                paddingLeft: line.startsWith('•') ? 14 : 0,
              }}>
                {line}
              </p>
            ))}
          </div>
        ))}

        <div style={{ marginTop: 40, paddingTop: 20, borderTop: '1px solid rgba(201,168,76,.1)', display: 'flex', gap: 20, flexWrap: 'wrap' }}>
          <Link href={`${prefix}/privacy`} style={{ fontSize: 12, color: 'rgba(201,168,76,.55)', textDecoration: 'none' }}>{c.privacy}</Link>
          <Link href={`${prefix}/refund`} style={{ fontSize: 12, color: 'rgba(201,168,76,.55)', textDecoration: 'none' }}>{c.refund}</Link>
        </div>

        <p style={{ marginTop: 16, fontSize: 11, color: 'rgba(200,195,220,.2)' }}>
          {`© ${new Date().getFullYear()} PilLAB. All rights reserved.`}
        </p>
      </div>
    </main>
  )
}
